name: Keep VNC Active

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep_vnc_active:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run VNC keep-alive script
      run: |
        python keep_vnc_active.py
      timeout-minutes: 13  # Stop after 13 minutes to allow for the next scheduled run
