name: CI with Tmate Debugging

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false

    - name: Debug Info
      run: |
        echo "Tmate session info:"
        echo "==================="
        cat /tmp/tmate.log
        echo "==================="
        echo "Environment variables:"
        env
        echo "==================="
        echo "Current directory contents:"
        ls -la
        echo "==================="
        echo "SSH client version:"
        ssh -V

    - name: Keep session alive
      run: sleep 1h
