name: tamate testtstttsttst

on:
  workflow_dispatch:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session and keep alive
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 350
      with:
        limit-access-to-actor: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Just under 6 hours to ensure the job can complete
