name: CI with Tmate Debugging

on:
  workflow_dispatch:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
    - name: Wait for user input
      run: |
        echo "Tmate session is active. Press any key to end the session."
        read -n 1 -s
