on:
  workflow_dispatch:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
        timeout-minutes: 30  # Adjust as needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Keep session alive and wait for user input
      run: |
        echo "Tmate session is active. Connect using the SSH command or web URL provided above."
        echo "This step will keep running for 6 hours or until you cancel the workflow."
        echo "You can safely connect to and disconnect from the tmate session multiple times."
        echo "To end the workflow early, cancel it from the GitHub Actions tab."
        sleep 21600  # 6 hours in seconds
